apiVersion: v1
kind: Service
metadata:
  name: semisecure
  namespace: semisecure
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: semisecure
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
